### ISSUE TITLE
The issue of compare_ssim function

### ISSUE THREAD

**Issue by Zheng222** [xinntao/BasicSR#19]
@xinntao  Hello, I found that you use the skimage.measure to compute SSIM index. But according to the offical API, this `compare_ssim` function should set gaussian_weight to True, sigma to 1.5, and use_sample_covariance to False to match the implementation of Matlab (Wang et. al.).
https://github.com/xinntao/BasicSR/blob/71635757505ef113bfba029441a4e35e59994a86/codes/utils/util.py#L90-L92

[skimage.measure.compare_ssim](http://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.compare_ssim)

**Comment by WolframRhodium** [comment]
According to the comments in scikit-image's `compare_ssim`, [a 13-tap Gaussian is used rather than a 11-tap Gaussian](https://github.com/scikit-image/scikit-image/blob/v0.14.1/skimage/measure/_structural_similarity.py#L156-L160), which was adapted by Zhou Wang's `ssim_index`. Therefore, `truncate` should be manually set to 3.0 in the `filter_args` dictionary at L160.

With the modification, the results from the two version of SSIM are identical on my computer.

**Comment by xinntao** [comment]
Hi @WolframRhodium 

Thank you very much for providing this useful information :smiley:.

I will try it later :-)
