### ISSUE TITLE
Dataset enlarge ratio

### ISSUE THREAD

**Issue by elezine** [xinntao/BasicSR#282]
Can you explain exactly what dataset_enlarge_ratio is doing? Is the default of 100 something to stick with? I'm just a bit confused about how this ratio changes the number of epochs, and if that matters.

**Comment by xinntao** [comment]
@elezine 

As stated [here](https://github.com/xinntao/BasicSR/blob/master/docs/Config.md)
>  dataset_enlarge_ratio  is for The ratio of enlarging dataset. For example, it will repeat 100 times for a dataset with 15 images
>  So that after one epoch, it will read 1500 times. It is used for accelerating data loader
>    since it costs too much time at the start of a new epoch

In practice, if you do not encounter the problem of long waiting time at the binning of each epoch for the dataloader, you can just set this to 1. Otherwise, you can increase this number. 

And the implementation details are https://github.com/xinntao/BasicSR/blob/2ae16da2140bcc4418081f52cc13edcc6df0d5c5/basicsr/data/data_sampler.py#L26-L28
