### ISSUE TITLE
Changing EDVR 'Reconstruction' module from official SR ResidualBlocks network to ESRGAN generator network?

### ISSUE THREAD

**Issue by yera217** [xinntao/BasicSR#304]
Dear Xintao,
Thank you for this repository. I have been studying it and running ESRGAN and EDVR models for a while.
In your EDVR publication, it was mentioned that the Reconstruction module can be replaced by other SR architectures like ESRGAN. I have pre-trained ESRGAN on my data, and now want to transfer it as a Reconstruction module of EDVR.
1) Should only `edvr_arch.py` file be changed for doing that?
2) Did I understand correctly, that during EDVR training only parameters of PCD and TSA are changing, whereas pre-trained Reconstruction (e.g. MSRGAN network) is used? If so, what model did you use in your official EDVR Reconstruction module?

**Comment by yera217** [comment]
And also, I tried to substitute 'Reconstruction' block (i.e. layers from `reconstruction.0.conv1.weight` to `reconstruction.9.conv2.bias`)  of EDVR official REDS_x4_M model by my pre-trained MSRGAN layers renaming `body `to `reconstruction`. When I test the obtained EDVR it outputs strange images like this. Do you have any ideas about what I might do wrong?
![image](https://user-images.githubusercontent.com/20044043/95745367-ca25fb00-0cb6-11eb-9cee-189b7bd1e116.png)
And its zoomed view:
![image](https://user-images.githubusercontent.com/20044043/95745442-e9248d00-0cb6-11eb-982a-b1ca4733055e.png)

**Comment by xinntao** [comment]
Hi @yera217 
1. You can change the reconstruction part by using other architectures. only changing edvr_arch.py is OK.
2. You should also finetune the whole network including the reconstruction part to obtain good results.
In the official EDVR, an SRResNet style arch is used for the reconstruction part. 

For the results above, I think you should also finetune the reconstruction part. otherwise, the input and output of the reconstruction part is strange and maybe meaningless.

**Comment by yera217** [comment]
HI, @xinntao !
Thank you for your suggestions. I substituted 10 reconstruction layers of official EDVR with my pre-trained 16 layers MSRGAN model and trained EDVR on that. After that, the results stabilized. However the resulting test images of modified EDVR have lower quality than MSRGAN. They have the same reconstruction architecture, but the results of EDVR worse. 
1) Is it possible that non-fine-tuned alignment and fusion modules of EDVR degrade the performance?
2) REDS dataset used for EDVR training in the paper has 120fps. I trained EDVR on 30fps video frames. How important is it to use high fps for training?  
3) Is it possible to put Reconstruction SR module before alignment and fusion modules? How do you think, Is it reasonable to do it?
Thank you)

**Comment by xinntao** [comment]
1. I think you need to finetune the whole network together, otherwise, the alignment-fusion model and the reconstruction cannot work in coordination well.
2. I have not tested other fps. If your testing and training datasets have the same fps, I think fps is not a crucial problem.
3. Our experiments show that it is better to put the alignment and fusion models ahead of the reconstruction model. 
furthermore, if we add a more residual block to the network, adding them to the reconstruction part could gain more benefits.

**Comment by yera217** [comment]
Thank you for your suggestions!
