### ISSUE TITLE
EDSR_Mx4 epoch question

### ISSUE THREAD

**Issue by ruby1ring** [xinntao/BasicSR#306]
![2020-10-12 11-13-11 的屏幕截图](https://user-images.githubusercontent.com/27205174/95701587-929a5d00-0c7c-11eb-9a36-192253175675.png)

In EDSR_Mx4 default option,train_set_len = 55370(using div2k),dataset_enlarge_ratio=100,batch_size_per_gpu=16(batchsize),
world_size=1,total_iters=300000.
so,the num_iter_per_epoch and the total_epochs are 346063 and 1.is this right things?especially the total_epochs is 1?

**Comment by xinntao** [comment]
First, the training in BasciSR repo is iter-based, in other words, we care about the **training iterations** rather than **training epochs**.  So, here we only use the total epoch number as a reference.

When we set a dataset enlarging ratio larger than 1. We treat the dataset that it "really" enlarge the dataset (actually it does not and it only repeats the dataset). So the num_iter_per_epoch will be larger (even sometimes larger than the total iters, but it does not affect the training) and the total epoch will be smaller (even to 1). 

I think we do not use epoch as a counter in image restoration tasks, so this process is OK (until now, I do not encounter any problems with this ). 

If you think this operation is unreasonable in some cases, please let me know these cases and your ideas about it. Thanks.

**Comment by ruby1ring** [comment]
thank for you answer.and I have two other questions.
first question,where the code about the val psnr output?
![问题2](https://user-images.githubusercontent.com/27205174/95828784-fa79a200-0d67-11eb-8b18-4248f245a0c5.png)
The second question，why is the wandb losses and psnr curve are not show?i only can see the system curve in wandb and exp logger data andtb_logger data is correct.As shown in the figure，i was using option
![2020-10-13 15-30-43 的屏幕截图](https://user-images.githubusercontent.com/27205174/95829726-33664680-0d69-11eb-9bb1-166895639fd1.png)
![问题1](https://user-images.githubusercontent.com/27205174/95829735-37926400-0d69-11eb-9bfb-28a750e0b40b.png)

**Comment by xinntao** [comment]
1. the codes are in each model file. For example, for SR model. it is in the https://github.com/xinntao/BasicSR/blob/f33864a7538496a6ded8aa1d75d68df6a91f5193/basicsr/models/sr_model.py#L125-L195

2.  Can you see the curves in https://wandb.ai/xintao/basicsr?workspace=user-xintao
the options are OK

maybe there is some other  settings in wandb?

**Comment by ruby1ring** [comment]
> 1. the codes are in each model file. For example, for SR model. it is in the https://github.com/xinntao/BasicSR/blob/f33864a7538496a6ded8aa1d75d68df6a91f5193/basicsr/models/sr_model.py#L125-L195
> 2. Can you see the curves in https://wandb.ai/xintao/basicsr?workspace=user-xintao
>    the options are OK
> 
> maybe there is some other settings in wandb?

The first problem has been solved by your guidance.
About the second problem, I can see all wandb curves in your wandb project. Maybe my computer has some bugs. I can not solve this problem when I try to change different versions of BasicSR and different wandb account, different option settings. This is a really strange thing.

**Comment by xinntao** [comment]
@ruby1ring  Did your local tensorboard log look good?

**Comment by ruby1ring** [comment]
yes,except losses and psnr curves,all look good.
and wandb logger is good.
The first picture is tensorboard command.
![2020-10-16 20-31-33 的屏幕截图](https://user-images.githubusercontent.com/27205174/96258701-fb703500-0fee-11eb-9f8e-a9ff31c0ac8c.png)
The second picture is Tensorboard curve.
![2020-10-16 20-31-47 的屏幕截图](https://user-images.githubusercontent.com/27205174/96258708-fe6b2580-0fee-11eb-8129-db1acf32520a.png)
The third picture is wandb log.
![2020-10-16 20-32-00 的屏幕截图](https://user-images.githubusercontent.com/27205174/96258968-70dc0580-0fef-11eb-9486-a445e56930c3.png)

**Comment by ruby1ring** [comment]
> First, the training in BasciSR repo is iter-based, in other words, we care about the **training iterations** rather than **training epochs**. So, here we only use the total epoch number as a reference.
> 
> When we set a dataset enlarging ratio larger than 1. We treat the dataset that it "really" enlarge the dataset (actually it does not and it only repeats the dataset). So the num_iter_per_epoch will be larger (even sometimes larger than the total iters, but it does not affect the training) and the total epoch will be smaller (even to 1).
> 
> I think we do not use epoch as a counter in image restoration tasks, so this process is OK (until now, I do not encounter any problems with this ).
> 
> If you think this operation is unreasonable in some cases, please let me know these cases and your ideas about it. Thanks.

For this question,I train two EDSR_Mx2 model that i set different enlarge_ratio numbers,1 and 100.The result have slight gap.
In my view,100 enlarge_ratio mean we train 100 times datasets in one epoch.100 epoch mean we train 1 time dataset in one epoch,and we train 100 times.There is no essential difference between them.because we both train 100 times datasets.Am I correct in saying this?

**Comment by xinntao** [comment]
@ruby1ring  Yes, you are right. Setting different enlarge_ratio numbers does not change the underlying data loading. 

Why do we need this parameter - enlarge_ratio?
Because for some machines (usually the cluster), restarting the data loaders after each epoch will cost too much time (maybe up to 10 minutes depends on the cluster env). So I set the parameter to decrease the restart times by lowering the total epoch numbers.
