### ISSUE TITLE
Confusion about l_d_cls_fake

### ISSUE THREAD

**Issue by musicrainie** [xinntao/BasicSR#32]
I'm confused about the category loss "l_d_cls_fake = self.cri_ce(cls_d_fake, self.var_cat)", which seems the same behaviour as "l_g_cls = self.l_gan_w * self.cri_ce(cls_g_fake, self.var_cat)" in generator and violation of the nature of discriminator. Shouldn't it be "l_d_cls_fake = self.cri_ce(cls_d_fake, 'background')" or something?  Thank you in advance.

**Comment by xinntao** [comment]
Hi @musicrainie,

If we have the discriminator and the classifier separately (i.e., they are two sperate networks), these two classification losses seem OK. Right?

Now, we merge them into one model with some shared feature extraction layers. And use two heads for distinguishing whether the input is real or fake, and classifying which category the input belongs to, respectively. 
Therefore, the discriminator here actually has two functions and two separate losses. And the classification loss will not influence the other loss (gan loss) since they use extra layers to produce their own outputs. 

The same design can be found in [ACGAN](https://github.com/gitlimlab/ACGAN-PyTorch/blob/master/main.py)

For real data:
https://github.com/gitlimlab/ACGAN-PyTorch/blob/4bd0405a4bd90b07548d4b84b57e24767d7cbf65/main.py#L186-L187

and for fake data:
https://github.com/gitlimlab/ACGAN-PyTorch/blob/4bd0405a4bd90b07548d4b84b57e24767d7cbf65/main.py#L209-L210
 
they both use their actual labels.
