### ISSUE TITLE
offsets in "Understanding Deformable Alignment in Video Super-Resolution"

### ISSUE THREAD

**Issue by notorious-eric** [xinntao/BasicSR#404]
Hi, could you please explain in "Understanding Deformable Alignment in Video Super-Resolution", which offset layer did you choose to visualize the learned offset similar to optical flow? There are many offsets in PCD align module. Thank you.

**Comment by ckkelvinchan** [comment]
Only the offsets in L1 are visualized.

**Comment by notorious-eric** [comment]
@ckkelvinchan Thank you for replying, I notice that apart from the pyramid offsets, there is also a cascading offset in the end. I wonder if you visualize the offset in the cascading part, as it is right after the offsets in L1. In my understanding there are two deformable alignments( pyramid and cascading), similar to two flow warping in this process?

**Comment by ckkelvinchan** [comment]
Yes, you can think in this way, but since after the pyramid alignment, the offsets are basically aligned, and therefore you can expect the offsets for cascading should be small. In fact, we visualized these offsets in our preliminary experiments, but they are small values that do not give much interpretable meaning.

**Comment by notorious-eric** [comment]
Thank you for explaining!

**Comment by EricMingze** [comment]
@ckkelvinchan Hi Kelvin,
I'm also trying to reproduce the result in https://github.com/XPixelGroup/BasicSR/issues/552. Can you please provide the script to regroup the offsets for visualization? Thank!! 

For reference: #552
