### ISSUE TITLE
generate_mod_LR_bic.m requires Matlab

### ISSUE THREAD

**Issue by MasterScrat** [xinntao/BasicSR#60]
Hello, I'm curious why `generate_mod_LR_bic.m` is implemented as Matlab script. Doesn't this require a paid Matlab license to run it?

Is there any reason why the downsampling is not implemented using `PIL`'s `Image.BICUBIC` resizing?

**Comment by xinntao** [comment]
@MasterScrat 
In super-resolution, many previous works test their methods on Matlab bicubic downsampling kernels. For a fair comparison, most of the following works still use the Matlab bicubic downsampling kernels. 
That's why we use the matlab bucubic kernel first.

The bicubic function in PIL or OpenCV is different from the bicubic function in Matlab.  You can find the differences in another issue: #15 .

For usage, you can also use other kernels. Usually, we apply a blur kernel before downsampling for anti-liasing.

**Comment by BK1024** [comment]
Hi xinntao, I looked into the wiki "MATLAB bicubic imresize". The difference between python-resized image and matlab-resized image seems to be significant (by the # of pixels). As I followed the link you put in issue #15 , on stack overflow post, it says to set the kernel constant A to -0.5 and to build opencv again. I wonder why you chose to re-implement the matlab function over building opencv package under a different kernel constant A? Are there any other caveats or pitfalls in the second option? Thank you!

**Comment by xinntao** [comment]
@BK1024 
I have tried the second option (long time ago), but I got different results from Matlab's ones.
Maybe there were some mistakes I made. If you could get the same results using the second option, please let me know. Thanks :-)

Also, an implementation without recompiling may be more user-friendly.

**Comment by BK1024** [comment]
I wonder if the difference between python-resized image and matlab-resized images are reasonable... say if I want to train the model on DIV2K. Do you have the PSNR or SSIM difference between matlab-resized image and python-resized image by your code? Thank you!

**Comment by BK1024** [comment]
Hi xinntao, I have run a few testcases on your python-implemented matlab resize function. It works just  fine, MSE difference is around 0.001 for image input (uint8). Thank you so much for your great work!
